# Cambio de Tamaño

Por momentos, llegará la ocasión en que el Vector que se esté trabajando no presenta las dimensiones adecuadas para nosotros, por lo que siempre es bueno hacer un **Cambio de Tamaño** según nuestro requisito.

Para esto NumPy posee la Función *reshape()* que se encarga de darle una nueva forma al Vector trabajado, siempre y cuando las nuevas dimensiones tengan una relación exacta. Para el primer ejemplo veremos la conversión de un Vector *Unidimensional* a uno *Multidimensional* de 2 Filas por 4 Columnas:

In [30]:
import numpy as np

listNumbers = [1,2,3,4,5,6,7,8]

myArray = np.array(listNumbers)

newArray = np.reshape(myArray, (2,4)) # Matriz de 2 x 4

newArray

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

En caso de que las dimensiones no tuviesen la relación exacta, un error se hará presente:

In [31]:
import numpy as np

listNumbers = [1,2,3,4,5,6,7,8]

myArray = np.array(listNumbers)

newArray = np.reshape(myArray, (3,2)) # Matriz de 3 x 2

newArray

ValueError: cannot reshape array of size 8 into shape (3,2)

Una forma simple de evitar esta clase de errores debido a que no tenemos una idea clara de cuáles podrían ser las dimensiones correctas, simplemente se puede declarar la Fila o Columna con el valor de -1 para que sea NumPy quien calcule el tamaño adecuado:

In [32]:
import numpy as np

listNumbers = [1,2,3,4,5,6,7,8]

myArray = np.array(listNumbers)

newArray = np.reshape(myArray, (-1,2)) # Matriz de 4 x 2

newArray

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

A su vez, un *Array Multidimensional* puede también llegar a cambiar de dimensiones. Para esto, veremos el ejemplo de una Matriz de 2 x 4 que cambia de dimensiones a 4 x 2:

In [33]:
import numpy as np

listNumbers = [[1,2,3,4],[5,6,7,8]]

myArray = np.array(listNumbers)

newArray = np.reshape(myArray, (4,2)) # Matriz de 4 x 2

newArray

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

También podemos transformar un *Array Multidimensional* a uno *Unidimensional* pero ahora implementando la Función *ravel()* que recibe de parámetro a la **Matriz**:

In [34]:
import numpy as np

listNumbers = [[1,2,3,4],[5,6,7,8]]

myArray = np.array(listNumbers)

newArray = np.ravel(myArray) # Convertir una Matriz a Vector

newArray

array([1, 2, 3, 4, 5, 6, 7, 8])

Oh bien implementando *reshape()* con la total de elementos del *Array Multidimensional*:

In [22]:
import numpy as np

listNumbers = [[1,2,3,4],[5,6,7,8]]

myArray = np.array(listNumbers)

newArray = np.reshape(myArray, 8) # Convertir una Matriz a Vector

newArray

array([1, 2, 3, 4, 5, 6, 7, 8])