# Función Arange

Otro modo de crear un *Array Unidimensional* o **Vector** de forma rápida es aprovechando la Función *arange* de NumPy. Al igual que la Función definida de Python *range* que genera un conjunto de números entre un Valor Inicial y un Valor Final menos uno, pudiendo o no especificar un Incremento entre los Valores; la Función *arange()* implementa la misma lógica con la diferencia de que el resultado siempre es un *Array*.

Para ejemplificar lo anterior, se generará un **Vector** de 0 a 11 pero que solo posea los elementos pares en ese segmento señalado:

In [75]:
import numpy as np

myArray = np.arange(0, 11, 2)

print("Vector: ", myArray)

Vector:  [ 0  2  4  6  8 10]


Obsérvese que si de los dos Valores (Iniciales y Finales), el primero es mayor que el segundo, se declara un Incremento **Negativo** y el **Vector** obtenido es decreciente:

In [76]:
import numpy as np

myArray = np.arange(10, -1, -2)

print("Vector: ", myArray)

Vector:  [10  8  6  4  2  0]


Pero si no se especifica el Incremento, al igual que en *range*, se sobreentiende que éste es 1:

In [77]:
import numpy as np

myArray = np.arange(0,11)

print("Vector: ", myArray)

Vector:  [ 0  1  2  3  4  5  6  7  8  9 10]


Y si sólo se especifica un único argumento, al igual que en *range*, se consideran todos los valores desde Cero hasta dicho Valor menos uno:

In [78]:
import numpy as np

myArray = np.arange(11)

print("Vector: ", myArray)

Vector:  [ 0  1  2  3  4  5  6  7  8  9 10]


# Función Zeros

En **Álgebra Lineal**, un Vector Nulo o **Vector Cero** se define como un Vector de longitud cero, que es una convención matemática útil para resolver ecuaciones vectoriales. El Vector Cero juega el papel de elemento neutro para la suma de Vectores. Si bien no tiene una dirección o sentido, es muy útil desde un punto de vista del álgebra de Vectores.

En NumPy la creación de un Vector de este estilo se realiza con la implementación de la Función *zeros()* cuyos valores son de Tipo *Float*.

In [79]:
import numpy as np

myArray = np.zeros(5)

myArray

array([0., 0., 0., 0., 0.])

El Vector con valores de Tipo *Float* no siempre es una opción, por lo que se puede definir el Vector con valores de Tipo *Int*:

In [80]:
import numpy as np

myArray = np.zeros((5), dtype = int)

myArray

array([0, 0, 0, 0, 0])

Finalmente, para una **Matriz Cero** se puede definir tanto Filas *(m)* como Columnas *(n)* e ingresarlas en *zeros()* como *Tupla*:

In [81]:
import numpy as np

m = 3

n = 2

myArray = np.zeros((m, n))

myArray

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

# Función Ones

La Función *ones()* regresa un Vector lleno de unos de Tipo *Float*:

In [82]:
import numpy as np

myArray = np.ones(5)

myArray

array([1., 1., 1., 1., 1.])

Y al igual que la Función *zeros()*, se puede definir el Vector *ones()* con valores de Tipo *Int* cambiando el datatype:

In [83]:
import numpy as np

myArray = np.ones((5), dtype = int)

myArray

array([1, 1, 1, 1, 1])

Finalmente, para una **Matriz de Unos** se puede definir tanto Filas *(m)* como Columnas *(n)* e ingresarlas en *ones()* como *Tupla*:

In [84]:
import numpy as np

m = 3

n = 2

myArray = np.ones((m, n))

myArray

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

# Función Linspace

La Función *linspace()* genera un *Array Unidimensional* o **Vector** formado por una cantidad *N <= 50* de números equiespaciados (conservan la misma distancia) entre un Valor Inicial y un Valor Final (que SI se incluye) de Tipo *Float*: *linspace(incio, final, número_valores)

In [85]:
import numpy as np

myArray = np.linspace(0, 10, 5)

myArray

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

Y al igual que la Funciones vistas, se puede definir el Vector *linspace()* con valores de Tipo *Int* cambiando el datatype:

In [86]:
import numpy as np

myArray = np.linspace(0, 10, 5, dtype=int)

myArray

array([ 0,  2,  5,  7, 10])

# Función Eye

Para comprender la Función *eye()* primero se debe comprender que es una **Matriz Diagonal** en Álgebra Lineal. Por definición, una Matriz Diagonal es un *Array Multidimensional* en la que todos los elementos que NO son la diagonal principal son cero y los elementos de la diagonal principal pueden ser nulos o no.

Habiendo comprendido lo anterior, la Función *eye()* recibe el valor correspondiente a las *columnas (n)* donde todos los elementos son del Tipo *Float* y la diagonal principal esta representada por el valor de uno. 

In [87]:
import numpy as np

myArray = np.eye(5)

myArray

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

A la Función *eye()* también se le puede asignar un valor correspondiente a las *filas (m)* respetando la diagonal principal:

In [88]:
import numpy as np

myArray = np.eye(3,2)

myArray

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

En ambos ejemplos, y como se señaló, la diagonal principal empieza en un *index* (0,0) pero esto no significa que no se pueda modificar. La variable *K* representaría el *index* de la diagonal que puede ser modificado en relación a los valores de las *columnas (n)*: 

In [89]:
import numpy as np

myArray = np.eye(5, k = 1)

myArray

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

Y al igual que la Funciones vistas, se puede definir la Matriz *eye()* con valores de Tipo *Int* cambiando el datatype:

In [90]:
import numpy as np

myArray = np.eye(5,dtype = int)

myArray

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])