# Números Aleatorios

Comúnmente, al momento de crear *Arrays*, es dificil pensar en cada uno de los elementos dentro del arreglo todo el rato que se desee gestar uno nuevo, por lo que la **Aletoridad** es la solución. Por lo general, se requiere generar números aleatorios que se escojan de manera relativamente uniforme y es por eso que NumPy posee dos Funciones útiles para estos casos.

# Función Rand

La Función *random.rand()* genera un *Array* del tamaño indicado, obteniendo números aleatorios extraídos del intervalo [0,1) a partir de una *distribución uniforme*:

In [12]:
import numpy as np

myArray = np.random.rand(5)

myArray

array([0.70693605, 0.49614381, 0.71476374, 0.72566054, 0.29865145])

A su vez se puede crear una Matriz Aleatoria declarando *Filas (m)* y *Columnas (n)*:

In [13]:
import numpy as np

myArray = np.random.rand(3,3)

myArray

array([[0.88924885, 0.45717604, 0.39203542],
       [0.14784324, 0.8470408 , 0.81660131],
       [0.3258954 , 0.11157563, 0.26600743]])

# Función Randn

Por su parte, la Función *random.randn* genera un *Array* del tamaño indicado, obteniendo números aleatorios extraídos del intervalo de *media 0 y varianza 1* a partir de una *distribución normal estándar*, también conocida como Gaussiana:

In [15]:
import numpy as np

myArray = np.random.randn(5)

myArray

array([ 0.33368533,  0.41073337,  0.02582788, -0.76624666,  0.39158133])

A su vez se puede crear una Matriz Aleatoria declarando *Filas (m)* y *Columnas (n)*:

In [16]:
import numpy as np

myArray = np.random.randn(3,3)

myArray

array([[-0.04301859, -0.15056638,  0.26955267],
       [ 0.71007243,  1.17282124,  0.12088185],
       [-0.11022858, -0.72951388, -0.29615881]])

# Función Randint

La Función *random.randint* genera un *Array* del tamaño indicado, obteniendo un número entero extraído de una *distribución discreta uniforme* entre los Intervalos indicados (del mismo modo que trabaja *range*):

In [26]:
import numpy as np

myArray = np.random.randint(0,100) # 0 a 99

myArray

58

A su vez podemos indicar si el *Array* se vuelve *Unidimensional* o *Multidimensional* definiendo el parámetro *size* como *Int* o *Tupla*:

In [27]:
import numpy as np

myArray = np.random.randint(0,100, size = 5) # 0 a 99

myArray

array([49, 92, 56, 55, 55])

In [28]:
import numpy as np

myArray = np.random.randint(0,100, size = (5,5)) # 0 a 99

myArray

array([[83, 26, 71, 14, 26],
       [32, 79, 52, 79, 56],
       [73, 50, 43, 33, 33],
       [ 4, 25, 16, 69, 39],
       [61, 42, 51, 90,  2]])

# Función Choise

Por último, la Función *random.choice* devuelve un *Array* del tamaño indicado, conteniendo dentro de sí una muestra de un *Array Unidimensional* cedido como argumento:

In [31]:
import numpy as np

listNames = ['Superman', 'Batman', 'Wonder Woman', 'Flash', 'Aquaman', 'Cyborg']

myArray = np.random.choice(listNames, 3)

myArray

array(['Aquaman', 'Batman', 'Cyborg'], dtype='<U12')

In [33]:
import numpy as np

listNames = ['Superman', 'Batman', 'Wonder Woman', 'Flash', 'Aquaman', 'Cyborg']

myArray = np.random.choice(listNames, (3,3))

myArray

array([['Wonder Woman', 'Flash', 'Cyborg'],
       ['Wonder Woman', 'Superman', 'Batman'],
       ['Batman', 'Batman', 'Cyborg']], dtype='<U12')